PracticeWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('music.urls')),
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.index, name='index'),

    # /music/<album_id>/
    path('<int:album_id>/', views.detail, name='detail'),

   # path('<int:album_id>', views.detail),

    # /music/<album_id>/favorite/
   #path('<int:album_id>/favorite/', name='favorite'),
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),


]

music/models.py
from django.db import models


# Create your models here.
#Red pk 1
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.urls import path
from . import views
from django.http import Http404
#from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
#from django.template import loader
from .models import Album, Song

# Create your views here.
def index(request):
    all_albums = Album.objects.all()
    #template = loader.get_template('music/index.html')
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)

    #return HttpResponse(template.render(context, request))

    #html = ''
    #for album in all_albums:
    #    url = '/music/' + str(album.id)
    #   html += '<a href = "' + url + '">'+ album.album_title +'</a><br>'
    #return HttpResponse(html)

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    #try:
    #    album = Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
    #    raise Http404("Album does not exist")
    return render(request, 'music/detail.html', {'album': album})

   #return HttpResponse("<h2>Details for Album id: " + str(album_id) + "</h2>")

# urlpatterns = [
#    path('', views.index, name = 'index'),
#
# ]


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src = '{{ album.album_logo }}'>

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
    <p><strong> {{ error_message }} </strong></p>
{% endif %}

<form action = "{% url 'music:favorite' album.id %}" method = "post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                 <img width ="20" height = "20" src="https://cdn.bulbagarden.net/upload/e/eb/Warp_Star.png">
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="favorite">
</form>

<!--<ul>
    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}
</ul> -->

music/templates/music/index.html
<!-- loads the path to your static files -->
{% load staticfiles %}
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>-->
<!--<link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}"/>-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


<nav class="navbar navbar-inverse"> <!--navbar-dafault for white-->
    <div class = "container-fluid">
        <!--Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="" >
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% if all_albums %}
        <h3>Here are all my Albums:</h3>
        <ul>
            {% for album in all_albums %}
            <li><a href ="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
           <!-- <li><a href ="./music/{{album.id}}/">{{album.album_title}}</a></li> -->
            {% endfor %}
        </ul>
{% else %}
        <h3>You don't have any albums</h3>
{% endif %}